### PR TITLE
Other client calculate

### PR DESCRIPTION
**Pull request by anoleto**
cb liat pec @10pc tar gw buff lg kalo aneh

### CODE REVIEW

**Comment by noemiowo** [comment]
@anoleto i would personally keep the length bonus, but make it not worth that much, as if the map is 52 minutes long it should maybe give a bit less pp than it does at the moment, but like not completely leave it out. just my personal idea, no need to actually go through with it, jus saying from a players perspective

**Comment by 10pc** [comment]
so fire

**Comment by anoleto** [comment]
should work ima merge

**Comment by anoleto** [comment]
wait fuck

**Pull request merged**
